### ISSUE TITLE
Italian short version on may shows full month name

### ISSUE THREAD

**Issue by phaberest** [jenssegers/date#341]
In a project based on [October](https://github.com/octobercms/october), which is using this package, when using the short version of "maggio", the italian name for May, the output is not shortened but instead it is shown in full.

**Comment by kylekatarnls** [comment]
Hello, that's not specific to Italian, it's a bug in Jenssegers/date fixed in 4.0.0. You just need to upgrade to the new version which inherit the translations from Carbon.

**Comment by phaberest** [comment]
Thank you Kyle, I'll check and upgrade

**Comment by kylekatarnls** [comment]
It sounds like october is locked to version 3, which is not relevant in my opinion, I will suggest them to upgrade.

**Comment by phaberest** [comment]
I'm afraid it's because they are still using Laravel 5.6 as a base, also Carbon is still not yet updated to v2.

I'm trying to override the versions in my composer.json hoping it won't break too much

**Comment by kylekatarnls** [comment]
Outch, that's a pity. With Laravel 8 in preparation, 5.6 is already far behind.

**Comment by phaberest** [comment]
Just re-checked and it's ~6.0, but the problem is the same 😕

**Comment by kylekatarnls** [comment]
Actually the next version of October will use Laravel 6.

And if they merge my PR: https://github.com/octobercms/library/pull/518

It will actually properly install jessengers 4 and Carbon 2:
https://github.com/octobercms/library/pull/518/checks?check_run_id=1042117191#step:8:57

**Comment by phaberest** [comment]
Amazing job, sincerely thank you Kyle! Closing this as the issue is not relevant to this project
